#!/usr/bin/env bash

# /tmp/gcalcli_agenda.txt has been generated by a cron executing:
# gcalcli agenda --tsv --nocolor "$(date)" "$(date --date='1 minute')" > /tmp/gcalcli_agenda_tmp.txt && cat /tmp/gcalcli_agenda_tmp.txt > /tmp/gcalcli_agenda.txt

FILE="/tmp/gcalcli_agenda.txt"
[ -s $FILE ] || exit
start=$(cat $FILE| tail -1|cut -d$'\t' -f2)
end=$(cat $FILE| tail -1|cut -d$'\t' -f4)
task=$(cat $FILE| tail -1|cut -d$'\t' -f5 | awk -v len=25 '{ if (length($0) > len) print substr($0, 1, len-3) "…"; else print; }')
echo " $start - $end  $task"
