#!/usr/bin/env sh

# echo "$(whoami) ALL=(root) NOPASSWD: sha256:$(shasum -a 256 $(which yabai) | cut -d " " -f 1) $(which yabai) --load-sa" | sudo tee /private/etc/sudoers.d/yabai
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config mouse_follows_focus off
yabai -m config focus_follows_mouse off
yabai -m config window_placement second_child
# yabai -m config window_topmost on
yabai -m config window_shadow on
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.0
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.95
yabai -m config insert_feedback_color 0xaad75f5f
yabai -m config split_ratio 0.50
yabai -m config auto_balance on
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# general space settings
# yabai -m config external_bar                 main:34:0
yabai -m config layout bsp
yabai -m config top_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 06

# space labels
yabai -m space 1 --label s1
yabai -m space 2 --label s2
yabai -m space 3 --label s3
yabai -m space 4 --label s4
yabai -m space 5 --label s5
yabai -m space 6 --label s6
yabai -m space 7 --label s7
yabai -m space 8 --label s8
yabai -m space 9 --label s9
yabai -m space 10 --label s10

# specific space settings
# yabai -m config --space 2 layout             stack
# yabai -m config --space 7 layout             float

# window rules
# yabai -m rule --add label=firefox app="^Firefox$" space=s1
# yabai -m rule --add label=emacs app="^Emacs$" space=2
# yabai -m rule --add app="^Kitty$" space=3
yabai -m rule --add label=prefs app="^System Preferences$" manage=off
yabai -m rule --add label=stats app="^Stats$" manage=off
# apple calendar auto complete popups
yabai -m rule --add label=calendar app="^Calendar$" title!="^Calendar$" manage=off
yabai -m rule --add label=choose app="^choose$" manage=off
yabai -m rule --add label=floater title="^floating-term" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label=maximized title="^fullscreen-term" manage=off grid=4:4:0:0:4:4
yabai -m rule --add label=chooser title="^chooser" manage=off grid="50:50:15:10:20:35" opacity=0.9
yabai -m rule --add label=emacs-launcher title="^emacs-launcher" manage=off opacity=0.9
yabai -m rule --add label=ankiadd title="^Add$" app="^Anki$" manage=off grid=4:4:1:1:2:2
yabai -m rule --add label=whatsappcall title="WhatsApp Voice Call$" manage=off grid=4:4:1:1:2:2

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# yabai -m signal --add event=application_activated app="^mpv$" action="/Users/Koe/Scripts/mpv_opacity"
# yabai -m signal --add event=application_deactivated app="^mpv$" action="/Users/Koe/Scripts/mpv_opacity"

# restore position of floating windows when they are manually unfloated
# ~/Scripts/yabai_restore.sh

echo "yabai configuration loaded.."
