#!/bin/bash
NCMP=$(mpc | grep "^\[playing\]" | awk '{print $1}' |  iconv -f utf-8 -t utf-8)
NUM_NCMP=$(mpc | head -1 | wc -c )
S_NCMP=$(mpc | head -1 | head -c 30| iconv -f utf-8 -t utf-8)

if [ "$NCMP" = "[playing]" ];then
    if [ "$NUM_NCMP" -lt 30 ];then
        echo " :$(mpc current) "
    else
        echo " : $S_NCMP…"
    fi
# else
#     echo " :Pause "
fi
