config.load_autoconfig()
config.source('../../../config.py')
config.source('../../../themes/base16-nord.config.py')
config.source('search-engines.py')
config.set("window.title_format", "{perc}{current_title}{title_sep} qutebrowser [WORK]")
