#!/usr/bin/env bash

# Pass interface as GUI to use choose or TUI to choose fzf
if [[ $INTERFACE == "GUI" ]]
then
    exec $*
else
    /opt/homebrew/bin/kitty --single-instance \
          --instance-group="chooser" \
          -o font_size=20 \
          -o window_padding_width=10 \
          -o adjust_line_height=10 \
          -d=~ \
          -T "chooser" \
          $*
fi
